config/routes.rb
Rails.application.routes.draw do
 
  get 'favorites/create'
  get 'favorites/destroy'
 root to: "toppages#index"
 
 get "login", to: "sessions#new"
 post "login", to: "sessions#create"
 delete "logout", to: "sessions#destroy"
 
 get "signup", to: "users#new"
 resources :users, only: [:show, :new, :create, :edit, :update] do
   member do
     get :followings
     get :followers
     get :pockets 
     get :likes
   end
 end

 resources :pockets, only: [:destroy, :update, :edit, :create, :new] do
  member do
    get :knowhows 
    get :posted_knowhows
    
   end
  end
 resources :knowhows, only: [:destroy, :update, :edit, :create, :show, :new] do
 member do
  post '/knowhow_posted' => 'knowhows#knowhow_posted'
  get :posted_knowhows
 end
end
 
 resources :relationships, only: [:create, :destroy]
 resources :favorites, only: [:create, :destroy]
 end

app/models/knowhow.rb
class Knowhow < ApplicationRecord
  belongs_to :pocket
  
  validates :content, presence: true, length: { maximum: 255 }
  validates :title, presence: true, length: { maximum: 50 }
  
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites, source: :user
  
  def self.search(search)
    if search
      where(["title LIKE ?", "%#{search}%"])
    else
      all
    end
  end
end

app/controllers/knowhows_controller.rb
class KnowhowsController < ApplicationController
  before_action :require_user_logged_in


  
  def destroy
    @knowhow = Knowhow.find(params[:id])
    @knowhow.destroy
    flash[:success] = "ポケットを削除しました。"
    redirect_back(fallback_location:root_path)
  end

  def create
    puts "ここを見ろ"
    p params
    @pocket = Pocket.find(params[:id])
    @knowhow = @pocket.knowhows.build(knowhow_params)
    if @knowhow.save
      flash[:success] = "ノウハウができました。"
      redirect_to  knowhows_pocket_path(@pocket)
      
    else
      flash.now[:danger] = "ノウハウができませんでした。"
      render "new"
  end
end

def new
  @knowhow = Knowhow.new
end

 def posted_knowhows
    @knowhows = Knowhow.where(posted: true)
    @search_knowhows = Knowhow.where(posted: true).page(params[:page]).search(params[:search])
  end

  def update
     @knowhow =  Knowhow.find(params[:id])
      if @knowhow.update(knowhow_params)
            flash[:success] = "ノウハウが更新されました"
            redirect_to knowhow_path(@knowhow)
        else
            flash.now[:danger] = "ノウハウが更新されませんでした"
            render "edit"
        end
  end

  def edit
  @knowhow =  Knowhow.find(params[:id])
  end
  
  def show
    @knowhow = Knowhow.find(params[:id])
  end
  
  def knowhow_posted
  	  @knowhow = Knowhow.find(params[:id])
	  @knowhow.posted = !@knowhow.posted
	  @knowhow.save
	end
	
	

 
  private
  
   def correct_pocket
       @pocket = Pocket.find(params[:id])
  @knowhow = @pocket.knowhows.find_by(id: params[:id])
end
  
  def knowhow_params
    params.require(:knowhow).permit(:content, :title, :posted)
  end
end

app/views/knowhows/_knowhows.html.erb
<ul class = "list-unstyled">
    <p>Myノウハウ一覧</p>
    <% knowhows.each do |knowhow| %>
    <li class = "media mb-3">
        <div class = "media-body">
            <div>
                <%= link_to knowhow.title, knowhow_path(knowhow) %>
                <span class = "text-muted">posted at <%= knowhow.created_at %></span>
            </div>
           
            <div>
                <% if @pocket == knowhow.pocket %>
                <%= link_to "Delete", knowhow, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-danger btn-sm" %>
               
                <% end %>
            </div>
        </div>
    </li>
    <% end %>
    <%= paginate knowhows %>
</ul>

app/views/knowhows/edit.html.erb
<% if logged_in? %>
<p>Myノウハウ編集ページ</p>
<div class = "row">
    <% if current_user == @knowhow.pocket.user %>
    <aside class = "col-sm-4">
        <%= form_with(model: @knowhow, local: true) do |f| %>
        <p>タイトル</p>
        <div class = "form-group">
            <%= f.text_area :title, class: "form-control", rows: 5 %>
        </div>
        
        <p>内容</p>
        <div class = "form-group">
            <%= f.text_area :content, class: "form-control", rows: 5 %>
        </div>
        <%= f.submit "編集OK", class: "btn btn-primary btn-block" %>
        <% end %>
    </aside>
    <% end %>
</div>
<% end %>

app/views/knowhows/knowhow_posted.js.erb
$('#true_or_false').html('<%= j(render("private_boolean")) %>');

app/views/knowhows/new.html.erb
<p>Myノウハウ作成ページ</p>
<% if logged_in? %>
<div class = "row">
    <aside class = "col-sm-4">
        <%= form_with(model: @knowhow, local: true) do |f| %>
        <div class = "form-group">
            <%= f.label :title, "タイトル" %>
            <%= f.text_area :title, class: "form-control", rows: 5 %>
        </div>
        
        <div class = "form-group">
            <%= f.label :content, "コンテンツ" %>
            <%= f.text_area :content, class: "form-control", rows: 5 %>
        </div>
        <%= hidden_field_tag :id, @pocket.id %>
        <%= f.submit "Post", class: "btn btn-primary btn-block" %>
        
        <%= link_to "ポケット一覧に戻る", pockets_user_path(current_user) %>
        <% end %>
    </aside>
    
</div>
<% end %>

app/views/knowhows/posted_boolean.html.erb
<% if @knowhow.posted == true %>
    <span class="true">true</span>
<% else %>
    <span class="false">false</span>
<% end %>

app/views/knowhows/posted_knowhows.html.erb
<ul class = "list-unstyled">
    <p>投稿されたノウハウたち</p>
    <br>
        <%= form_tag(posted_knowhows_pocket_path, :method => "get") do %>
        <p>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "検索", :title => nil %>
        </p>
        <% end %>
        <br>
        <% if @search_knowhows %>
            <% @search_knowhows.each do |knowhow| %>
            <li class = "media mb-3">
                     <%= image_tag knowhow.pocket.user.image.to_s %>
                <div class = "media-body">
                    <div>
                         <%= link_to knowhow.pocket.user.name, user_path(knowhow.pocket.user) %>
                        <span class = "text-muted">posted at <%= knowhow.created_at %></span>
                    </div>
                    <div>
                        <%= link_to knowhow.title, knowhow_path(knowhow) %>
                    </div>
                    <div>
                          <%=render 'favorites/favorite_button', knowhow: knowhow %>
                    </div>
                </div>
            </li>
        </ul>
            <% end %>
        <% else %>
        
    <% @knowhows.each do |knowhow| %>

    <li class = "media mb-3">
        <%= image_tag knowhow.pocket.user.image.to_s %>
        <div class = "media-body">
            <div>
                <div>
                    
                    <%= knowhow.pocket.user.name %>
                     <span class = "text-muted">posted at <%= knowhow.created_at %></span>
                </div>
                <div>
                <%= link_to knowhow.title, knowhow_path(knowhow) %>
                </div>
            </div>
        </div>
    </li>
    <% end %>
    <% end %>
   
</ul>


         
     

app/views/knowhows/show.html.erb
<p>ノウハウ詳細</p>
 <li class = "media mb-3">
        <div class = "media-body">
            <div>
                <span class= "text-muted">create at <%= @knowhow.created_at %></span>
            </div>
            <div>
                <p>タイトル</p>
                <p><%= @knowhow.title %></p>
            </div>
            <div>
                <p>内容</p>
                <p><%= @knowhow.content %></p>
            </div>
            
            <div>
                <%=render 'favorites/favorite_button', knowhow: @knowhow %>
            </div>
            
            <br>
            
            <% if current_user == @knowhow.pocket.user %>
            <p>
              <strong>ノウハウ掲示板に投稿:</strong>
                <%= check_box_tag 'knowhow[posted]', true, @knowhow.posted, {
                    onchange: '$(this).data("params", "knowhow[posted]=" + this.checked)',
                    data: {
                        url: knowhow_url + '/knowhow_posted/',
                        method: :post,
                        remote: true
                    }
                } %>
                
                
                
              <span id="true_or_false">
                  <% if @knowhow.posted == true %>
                     <span class="true">posted</span>
                  <% else %>
                     <span class="false">not posted</span>
                  <% end %>
              </span>
            </p>
           
        
            <div>
              
                <%= link_to "タイトル 内容を編集する", edit_knowhow_path(@knowhow),  class: "btn btn-primary btn-sm" %>
            </div>
             <% end %>
            <div>
               <%= link_to "ポケット一覧", pockets_user_path(current_user) %>
            </div>
            
            <div>
               <%= link_to "ノウハウ掲示板", posted_knowhows_knowhow_path %>
            </div>
        </div>
    </li>

app/views/knowhows/update.html.erb
<h1>Knowhows#update</h1>
<p>Find me in app/views/knowhows/update.html.erb</p>