config/routes.rb
Rails.application.routes.draw do
 
  get 'favorites/create'
  get 'favorites/destroy'
 root to: "toppages#index"
 
 get "login", to: "sessions#new"
 post "login", to: "sessions#create"
 delete "logout", to: "sessions#destroy"
 
 get "signup", to: "users#new"
 resources :users, only: [:show, :new, :create, :edit, :update] do
   member do
     get :followings
     get :followers
     get :pockets 
     get :likes
   end
 end

 resources :pockets, only: [:destroy, :update, :edit, :create, :new] do
  member do
    get :knowhows 
    get :posted_knowhows
    
   end
  end
 resources :knowhows, only: [:destroy, :update, :edit, :create, :show, :new] do
 member do
  post '/knowhow_posted' => 'knowhows#knowhow_posted'
  get :posted_knowhows
 end
end
 
 resources :relationships, only: [:create, :destroy]
 resources :favorites, only: [:create, :destroy]
 end

app/models/pocket.rb
class Pocket < ApplicationRecord
  belongs_to :user
  
  has_many :knowhows
  has_many :knowhows, dependent: :destroy
  
  validates :pocket_name, presence: true, length: { maximum: 100 }
  
  
end

app/controllers/pockets_controller.rb
class PocketsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy, :update, :edit]

  def destroy
    @pocket.destroy
    flash[:success] = "ポケットを削除しました。"
    redirect_back(fallback_location:root_path)
  end

  def create
    @pocket = current_user.pockets.build(pocket_name_params)
    if @pocket.save
      flash[:success] = "ポケットができました。"
      redirect_to pockets_user_path(current_user.id)
    else
      flash.now[:danger] = "ポケットができませんでした。"
      render :"new"
  end
end

 

  def update
     @pocket =  Pocket.find(params[:id])
      if @pocket.update(pocket_name_params)
            flash[:success] = "Pocketが更新されました"
            redirect_to pockets_user_path(current_user.id)
        else
            flash.now[:danger] = "Pocketが更新されませんでした"
            render "edit"
        end
  end

  def edit
  @pocket =  Pocket.find(params[:id])
  @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def knowhows
     @pocket = Pocket.find(params[:id])
     @knowhow = @pocket.knowhows.build
    @knowhows = @pocket.knowhows.order(id: :desc).page(params[:page])
  end
  
  def new
    @pocket = Pocket.new
end

  def posted_knowhows
    @knowhows = Knowhow.where(posted: true)
    @search_knowhows = Knowhow.where(posted: true).page(params[:page]).search(params[:search])
  end
  
  def pocket_name_params
    params.require(:pocket).permit(:pocket_name)
  end
  
  def correct_user
  @pocket = current_user.pockets.find_by(id: params[:id])
  unless @pocket
  redirect_to root_path
  end
end

 
  private
  
  def correct_pocket
      @pocket = current_user.pocket.find(params[:id])
  @knowhow = @pocket.knowhows.find_by(id: params[:id])
end

  
  def knowhow_params
    params.require(:knowhow).permit(:content, :title)
  end
end

app/views/pockets/_pockets.html.erb
<ul class = "list-unstyled">
    <p>Myポケット一覧</p>
    <% pockets.each do |pocket| %>
    <li class = "media mb-3">
         
        <%= image_tag @user.image.to_s %>
        <div class = "media-body">
            <div>
                <%= link_to pocket.user.name, user_path(pocket.user) %>
                <span class= "text-muted">create at <%= pocket.created_at %></span>
            </div>
            <div>
                <p><%= link_to pocket.pocket_name, knowhows_pocket_path(pocket) %></p>
            </div>
            <div>
                <% if current_user == @pocket.user %>
                <%= link_to "Delete", pocket, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-danger btn-sm" %>
                <%= link_to "Edit", edit_pocket_path(pocket),  class: "btn btn-primary btn-sm" %>
                <% end %>
            </div>
        </div>
    </li>
    <% end %>
    <%= paginate pockets %>
</ul>

app/views/pockets/edit.html.erb
<% if logged_in? %>
<p>Myポケット編集ページ</p>
<div class = "row">
    <% if current_user == @pocket.user %>
    <aside class = "col-sm-4">
        <%= form_with(model: @pocket, local: true) do |f| %>
        <div class = "form-group">
            <%= f.text_area :pocket_name, class: "form-control", rows: 5 %>
        </div>
        <%= f.submit "編集OK", class: "btn btn-primary btn-block" %>
        <% end %>
    </aside>
    <% end %>
</div>
<% end %>

app/views/pockets/knowhows.html.erb
<p>Myノウハウ作成ページ</p>
<% if logged_in? %>
<div class = "row">
    <aside class = "col-sm-4">
        <%= form_with(model: @knowhow, local: true) do |f| %>
        <div class = "form-group">
            <%= f.label :title, "タイトル" %>
            <%= f.text_area :title, class: "form-control", rows: 5 %>
        </div>
        
        <div class = "form-group">
            <%= f.label :content, "コンテンツ" %>
            <%= f.text_area :content, class: "form-control", rows: 5 %>
        </div>
        <%= hidden_field_tag :id, @pocket.id %>
        <%= f.submit "Post", class: "btn btn-primary btn-block" %>
        
        <%= link_to "ポケット一覧に戻る", pockets_user_path(current_user) %>
        <% end %>
    </aside>
    <div class = "col-sm-8">
        <%= render "knowhows/knowhows", knowhows: @knowhows %>
    </div>
</div>
<% end %>

app/views/pockets/new.html.erb
<p>Myポケット作成ページ</p>
<% if logged_in? %>
<div class = "row">
    <aside class = "col-sm-5">
        
        <%= form_with(model: @pocket, local: true) do |f| %>
        <div class = "form-group">
            <%= f.label :pocket_name, "ポケット名" %>
            <%= f.text_area :pocket_name, class: "form-control", rows: 5 %>
        </div>
        <%= f.submit "Post", class: "btn btn-primary btn-block" %>
        <% end %>
    </aside>
</div>
<% end %>

app/views/pockets/show.html.erb
<% if logged_in? %>
<div class = "row">
    <aside class = "col-sm-4">
        <%= form_with(model: @pocket, local: true) do |f| %>
        <div class = "form-group">
            <%= f.text_area :pocket_name, class: "form-control", rows: 5 %>
        </div>
        <%= f.submit "Post", class: "btn btn-primary btn-block" %>
        <% end %>
    </aside>
    <div class = "col-sm-8">
        <%= render "pockets/pockets", pockets: @pockets %>
    </div>
</div>
<% end %>