config/routes.rb
Rails.application.routes.draw do
 
  get 'favorites/create'
  get 'favorites/destroy'
 root to: "toppages#index"
 
 get "login", to: "sessions#new"
 post "login", to: "sessions#create"
 delete "logout", to: "sessions#destroy"
 
 get "signup", to: "users#new"
 resources :users, only: [:show, :new, :create, :edit, :update] do
   member do
     get :followings
     get :followers
     get :pockets 
     get :likes
   end
 end

 resources :pockets, only: [:destroy, :update, :edit, :create, :new] do
  member do
    get :knowhows 
    get :posted_knowhows
    
   end
  end
 resources :knowhows, only: [:destroy, :update, :edit, :create, :show, :new] do
 member do
  post '/knowhow_posted' => 'knowhows#knowhow_posted'
  get :posted_knowhows
 end
end
 
 resources :relationships, only: [:create, :destroy]
 resources :favorites, only: [:create, :destroy]
 end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: { case_sensitive: false }
    
    has_secure_password
    
    mount_uploader :image, ImageUploader
    
    has_many :pockets
    
    has_many :relationships
    has_many :followings, through: :relationships, source: :follow
    has_many :reverses_of_relationship, class_name: "Relationship", foreign_key: "follow_id"
    has_many :followers, through: :reverses_of_relationship, source: :user
    
    has_many :knowhows
    has_many :favorites
    has_many :likes, through: :favorites, source: :knowhow

    def favorite(knowhow)
   favorites.find_or_create_by(knowhow_id: knowhow.id)
 end
 
 def unfavorite(knowhow)
   favorite = favorites.find_by(knowhow_id: knowhow.id)
   favorite.destroy if favorite
end

  def favoriting?(knowhow)
  self.likes.include?(knowhow)
  end
    
    def follow(other_user)
        unless self == other_user
        self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  
  def feed_pockets
      Pockets.where(user_id: self.id)
  end
  
    def unfollow(other_user)
        relationship = self.relationships.find_by(follow_id: other_user.id)
        relationship.destroy if relationship
    end
    
    def following?(other_user)
        self.followings.include?(other_user)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :edit, :update, :followings, :followers]
  before_action :current_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit]
  def show
    @user = User.find(params[:id])
    @users = User.order(id: :desc).page(params[:page]).per(25)
     @followers = @user.followers.page(params[:page])
    counts(@user)
    @followings = @user.followings.page(params[:page])
    counts(@user)
    
    #@knowhow = Knowhow.find(params[:id])
    @knowhows = @user.likes.page(params[:page])
   
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
     
    if @user.save
      flash[:success] = "ユーザーを登録しました。"
      redirect_to @user
    else
      flash.now[:danger] = "ユーザーの登録に失敗しました。"
      render :new
    end
    
  end

  
  def edit
    @user = User.find(params[:id])
  
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "編集完了しました"
      redirect_to @user
    else
      flash.now[:danger] = "編集できませんでした。"
      render "edit"
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
  
  def pockets
     @user = User.find(params[:id])
    @pocket = current_user.pockets.build
    @pockets = current_user.pockets.order(id: :desc).page(params[:page])
  end
  
 private
 
  def correct_user
    @user = current_user
    unless @user
    redirect_back(fallback_location: root_path)
  end
  end
  
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_url(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    end
end

app/views/users/_users.html.erb
<% if users.any? %>
    <ul class = "list-unstyled">
        <% users.each do |user| %>
        
        <li class = "media">
            <img class = "mr-2 rounded" src = 
            "
            <%= gravatar_url(user, { size: 50 }) %>
            " alt = "">
            <div class = "media-body">
                <div>
                    
                    <%= user.name %>
                    
                </div>
                
                <div>
                    <p>
                        <%= link_to "View profile", user_path(user) %>
                    </p>
                </div>
            </div>
        </li>
        
        <% end %>
        
    </ul>
    
    <%= paginate users %>
    
    <% end %>

app/views/users/edit.html.erb
<h1>ユーザー編集</h1>

<div class= "row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for @user do |f| %>
        
        
       
        <div>
        <%= image_tag @user.image.to_s %>
        </div>
        
        <% if current_user == @user %>
        <div>
       <%=f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
        </div>
        
        <div>
            <%= f.label :image %>
            <%= f.file_field :image %>
        </div>
        
        
        <%= f.submit "編集OK",　class: "btn btn-primary" %>
        <% end %>
        
        <% end %>
        
        
    </div>
</div>

app/views/users/followers.html.erb
  <a href="
<%= followers_user_path(@user) %>
" class="nav-link 
<%= 'active' if current_page?(followers_user_path(@user)) %>
">Followers <span class="badge badge-secondary">
<%= @count_followers %>
</span></a>

<%= render 'users', users: @followers %>

app/views/users/followings.html.erb
  <a href="
<%= followings_user_path(@user) %>
" class="nav-link 
<%= 'active' if current_page?(followings_user_path(@user)) %>
">Followings  <span class="badge badge-secondary">
<%= @count_followings %>
</span></a>

<%= render 'users', users: @followings %>

app/views/users/new.html.erb
<div class = "text-center">
    <h1>Signup</h1>
</div>

<div class = "row">
    <div class = "col-sm-6 offset-sm-3">
        
<%= form_with(model: @user, local: true) do |f| %>
<%= render "layouts/error_messages", model: f.object %>


        <%= form_with(model: @user, local: true) do |f| %>
        
        <div class = "form-group">
            <%= f.label :name, "ユーザー名" %>
            <%= f.text_field :name, class: "form-control" %>
        </div>
        
        <div class = "form-group">
            <%= f.label :email, "Eメール" %>
            <%= f.email_field :email, class: "form-control" %>
        </div>
        
        <div class = "form-group">
            <%= f.label :password, "パスワード" %>
            <%= f.password_field :password, class: "form-control" %>
        </div>
        
        <div cladd = "form-group">
            <%= f.label :password_confirmation, "パスワード確認" %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
        
        <br>
        <%= f.submit "Sign up", class: "btn btn-primary btn-block" %>
        
        
        <% end %>
    </div>
</div>
<% end %>

app/views/users/pockets.html.erb
<p>Myポケット作成ページ</p>
<% if logged_in? %>
<div class = "row">
    <aside class = "col-sm-5">
        
        <%= form_with(model: @pocket, local: true) do |f| %>
        <div class = "form-group">
            <%= f.label :pocket_name, "ポケット名" %>
            <%= f.text_area :pocket_name, class: "form-control", rows: 5 %>
        </div>
        <%= f.submit "Post", class: "btn btn-primary btn-block" %>
        <% end %>
    </aside>
    <div class = "col-sm-7">
        <%= render "pockets/pockets", pockets: @pockets %>
    </div>
</div>
<% end %>

app/views/users/show.html.erb
<div class = "row">
    <aside class = "col-sm-4">
        <div class = "card">
            <div class = "card-header">
                <h3 class = "card-title"><%= @user.name %></h3>
            </div>
            <div class = "card-body">
               
         <%= image_tag @user.image.to_s %>
        
                
            </div>
        </div>
    </aside>
  <class = "col-sm-8">
     <p>みんなのノウハウ</p>
     
            <% @knowhows.each do |knowhow| %>
      <div >
            <div>
                <div>
                    <%= link_to knowhow.pocket.user.name, user_path(knowhow.pocket.user) %>
                     <span class = "text-muted">posted at <%= knowhow.created_at %></span>
                </div>
                
                <div>
                <%= link_to knowhow.title, knowhow_path(knowhow) %>
                <%=render 'favorites/favorite_button', knowhow: knowhow %>
                </div>
            </div>
        </div>
       </li>
       <% end %>
  </class>

       </ul>
</div>